name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: download toolchain
      run: |
        mkdir toolchain
        cd toolchain
        wget -q https://github.com/andestech/Andes-Development-Kit/releases/download/ast-v3_2_1-release-linux/nds64le-elf-newlib-v5d.txz
        wget -q https://github.com/andestech/Andes-Development-Kit/releases/download/ast-v3_2_1-release-linux/nds64le-linux-glibc-v5d.txz
        tar -xf nds64le-elf-newlib-v5d.txz
        tar -xf nds64le-linux-glibc-v5d.txz

    - name: build vmlinux
      env:
        secret: ${{ secrets.HZY_TOKEN }}
        ARCH: riscv
        CROSS_COMPILE: riscv64-linux-
      run: |
        export PATH=$PWD/toolchain/nds64le-elf-mculib-v5d/bin:$PWD/toolchain/nds64le-linux-glibc-v5d/bin:$PATH
        git clone --depth 1 https://oauth2:$secret@github.com/kendryte/k510_linux_kernel.git
        cd k510_linux_kernel
        make k510_defconfig
        make vmlinux

    - name: configure
      env:
        ARCH: riscv
        CROSS_COMPILE: riscv64-linux-
      run: |
        export PATH=$PWD/toolchain/nds64le-elf-mculib-v5d/bin:$PWD/toolchain/nds64le-linux-glibc-v5d/bin:$PATH
        mkdir build
        cd build
        ../configure --host=riscv64-linux --with-payload=../k510_linux_kernel/vmlinux
      
    - name: make
      env:
        ARCH: riscv
        CROSS_COMPILE: riscv64-linux-
      run: |
        export PATH=$PWD/toolchain/nds64le-elf-mculib-v5d/bin:$PWD/toolchain/nds64le-linux-glibc-v5d/bin:$PATH
        cd build
        make
